<?php
/*
 * This file is generated by:
 * php artisan create_user_info_table \
 * >make:miration --create='user_info'
 *
 *then,you can use the directive of "php artisan migrate"
 *to create new table you need;
 *
 * */

/*
 * This file is generated by:
 * php artisan create_user_info_table \
 * >make:miration --table='user_info'
 *执行--table,而不是--create,将不会创建新表,只是修改表而已
 *
 **/

/*
 * This file is generated by:
 * php artisan create_user_info_table \
 * >make:miration;
 *只会给你创建两个空的up与down方法
 **/

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUserInfoTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		/*Notes:
		 *Schema是结构生成器,下面的代码既是创建一个表
		 *The type of second argument is 'function'
		 *The syntax of this sentence is very like "JavaScript"
		 */
		Schema::create('user_info', function(Blueprint $table)
		{
			$table->increments('user_id');//定义一些表的字段
			$table->char('user_name',20);
			$table->char('user_phone',11);
			/*Two fields will be generated in the table
			 *One name is "created_at",
			 *The other is "updated_at"
			 */
			$table->timestamps();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('user_info');
	}

}
